server:
  port: 8003

spring:
  application:
    name: provider-user


eureka:
  instance:
    prefer-ip-address: true
    instance-id: provider-user8003
  client:
    service-url:
       defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/
    healthcheck:
      enabled: true



info:
  app.name: provider-user-springcloud
  company.name: chenyj
  build.artifactId: $project.artifactId$
  build.version: $project.version$