server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false #不把自己注册到eureka上
    fetch-registry: false #不从eureka上获取注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  security:
    user:
      name: user
      password: 123
#    enabled: false #开启关闭security安全配置