server:
  port: 8201

spring:
  application:
    name: consumer-order

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/
    healthcheck:
      enabled: true

applicationName: http://provider-user/