server:
  port: 8201

spring:
  application:
    name: consumer-order

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      #      defaultZone: http://user:123@localhost:8761/eureka/
      defaultZone: http://@localhost:8761/eureka/
    healthcheck:
      enabled: true

applicationName: http://PROVIDER-USER/